### ISSUE TITLE
[undefined]ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/latest/chromedriver_mac64.zip

### ISSUE THREAD

**Issue by munyamunya** [ElSnoMan/pyleniumio#286] opened 2022-10-17 11:10 UTC
I'm writing your sample code of "test_qap_dev.py".
But the following error happened.
Maybe this isn't your problem, but do you have any input on how to resolve this phenomenon?

-----

./tests/test_qap_dev.py::test_carlos_is_on_leadership Failed: [undefined]ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/latest/chromedriver_mac64.zip
py = <pylenium.driver.Pylenium object at 0x7fb5bab82970>

    def test_carlos_is_on_leadership(py):
>       py.visit('https://qap.dev')

tests/test_qap_dev.py:2: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.9/site-packages/pylenium/driver.py:362: in visit
    self.webdriver.get(url)
venv/lib/python3.9/site-packages/pylenium/driver.py:235: in webdriver
    return self.init_webdriver() if self._webdriver is None else self._webdriver
venv/lib/python3.9/site-packages/pylenium/driver.py:203: in init_webdriver
    self._webdriver = webdriver_factory.build_from_config(self.config)
venv/lib/python3.9/site-packages/pylenium/webdriver_factory.py:147: in build_from_config
    return build_chrome(seleniumwire_options=config.driver.seleniumwire_options, **_config)
venv/lib/python3.9/site-packages/pylenium/webdriver_factory.py:196: in build_chrome
    service=ChromeService(local_path or ChromeDriverManager(version=version).install()),
venv/lib/python3.9/site-packages/webdriver_manager/chrome.py:39: in install
    driver_path = self._get_driver_path(self.driver)
venv/lib/python3.9/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
venv/lib/python3.9/site-packages/webdriver_manager/core/download_manager.py:28: in download_file
    response = self._http_client.get(url)
venv/lib/python3.9/site-packages/webdriver_manager/core/http.py:33: in get
    self.validate_response(resp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

resp = <Response [404]>

    @staticmethod
    def validate_response(resp: requests.Response):
        status_code = resp.status_code
        if status_code == 404:
>           raise ValueError(f"There is no such driver by url {resp.url}")
E           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/latest/chromedriver_mac64.zip

venv/lib/python3.9/site-packages/webdriver_manager/core/http.py:16: ValueError

**Comment by ElSnoMan** [comment] 2022-10-17 14:22
This is duplicate of #278, but if you look in there you'll see some workarounds since the problem is with webdriver manager. Thanks!

**Comment by munyamunya** [comment] 2022-10-18 00:12
thanks @ElSnoMan 
If you are managing with a different failure ticket, please Close this one.

**Closed** 2022-10-18 17:19 UTC
Labels: bug, duplicate
